name: bushido
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  appwrite: ^19.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  logger: ^2.6.1
  shared_preferences: ^2.5.3
  stacked: ^3.5.0
  stacked_services: ^1.6.0

dev_dependencies:
  freezed: ^2.5.7
  hive_generator: ^2.0.1
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true
