name: bushido
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  appwrite: ^17.1.0
  stacked: 3.4.1
  stacked_services: ^1.6.0
  logger: ^2.6.2
  shared_preferences: ^2.5.3
  freezed_annotation: 2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  # Oudere versies die perfect werken met analyzer 5.x
  freezed: 2.4.1
  json_serializable: 6.7.1
  stacked_generator: ^1.3.3
  isar_generator: ^3.1.0+1
  mockito: ^5.4.1
  golden_toolkit: ^0.15.0

dependency_overrides:
  analyzer: 5.13.0
  source_gen: 1.4.0
  path: 1.9.0
  dart_style: 2.3.1