name: bushido
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  appwrite: ^17.1.0
  stacked: 3.4.1
  stacked_services: ^1.6.0
  logger: ^2.6.2
  shared_preferences: 2.3.2
  freezed_annotation: ^2.4.4 # Precies wat de compiler vroeg
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.15
  freezed: 2.5.7
  json_serializable: 6.7.1
  stacked_generator: ^1.3.3
  mockito: 5.4.4
  golden_toolkit: ^0.15.0